# Generated by Django 4.1.3 on 2022-12-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_song_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
