# Generated by Django 4.1.3 on 2022-12-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_alter_song_song_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist_name',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='audio_file',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='image_link',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_link',
        ),
    ]
