# Generated by Django 4.1.3 on 2022-12-28 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_song_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
